### PR TITLE
Enable cryptodisk

### PR DESCRIPTION
**Pull request by shizonic**
For encrypted devices the grub environment variable `GRUB_ENABLE_CRYPTODISK` has to be set to `y` in order to generate the correct grub entry. If this environment variable isn't set the essential part of `cryptomount -u` is missing.

### CODE REVIEW

**Comment by pauldotknopf** [comment]
Have you verified this works with non-encrypted boot volumes?

**Comment by shizonic** [comment]
No not yet, but I can if you suggest. Another option would be an additional cli flag and a condition. I may work on this if you like. I want also add a flag for a custom configPath (/etc/darch).

EDIT:
But as far as I know GRUB_ENABLE_CRYPTODISK does only be used by GRUB if you really have an encrypted boot partition. However I will confirm that if I have tested it.

**Comment by pauldotknopf** [comment]
Thanks! Let me know the results. I'm fine with a cli flag.

**Comment by shizonic** [comment]
Any suggestions?

**Comment by pauldotknopf** [comment]
LGTM

**Comment by pauldotknopf** [comment]
I've deployed ```0.21.0```, glad you got everything working!

**Comment by shizonic** [comment]
Thank you @pauldotknopf for merging and that you are satisfied with my little contibution. I would like to help out more if you are interested. Thanks too for the deployment of release 0.21.0. Are planning to update the void package too?

**Pull request merged**
